dist: xenial
os:
  - linux
language: node_js
node_js:
  - stable
cache: yarn
script:
  - yarn test

addons:
  ssh_known_hosts: h84xu.ftp.infomaniak.com

before_deploy:
  - npm install -g gulp-cli
  - yarn pull-assets
  - yarn build
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build h84xu_leomaradan@h84xu.ftp.infomaniak.com:$SSH_DIRECTORY
    on:
      branch: master
