dist: xenial
os:
  - linux
language: node_js
node_js:
  - stable
cache: yarn

script:
  - yarn test

before_deploy:
  - npm install -g gulp-cli
  - yarn pull-assets
  - yarn build

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
