export type IClans =
  | ""
  | "BannerLords"
  | "HighElves"
  | "SacredOrder"
  | "OgrynTribes"
  | "LizardMen"
  | "Skinwalkers"
  | "Orcs"
  | "Demonspawn"
  | "UndeadHordes"
  | "DarkElves"
  | "KnightsRevenant"
  | "Barbarians"
  | "Dwarves"
  | "Shadowkin";
